apiVersion: apps/v1
kind: Deployment
metadata:
  name: sepsis-ui
spec:
  selector:
    matchLabels:
      app: sepsis-ui
  template:
    metadata:
      labels:
        app: sepsis-ui
    spec:
      containers:
      - name: sepsis-ui
        image: quay.io/anattama/sepsis-ui
        env:
          - name: "NGINX_HTTP_PORT_NUMBER"
            value: "8080"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
